{% set name = "napari-geoscience-viewer" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-geoscience-viewer-{{ version }}.tar.gz
  sha256: b65b45838d6a6b6f3f06ba5de2bd8bc286a87bb6a8ca6accc20a631eaf1e02ab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - h5py
    - magicgui
    - napari-geojson
    - napari
    - netcdf4
    - numpy
    - python >=3.8
    - shapely
    - xarray    

test:
  imports:
    - napari_geoscience_viewer
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yunhal/napari-geoscience-viewer
  summary: A napari plugin for quick-viewing HDF5 and NetCDF files
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - yunhal
